---
name: GitLab
version: dev
slug: gitlab
description: GitLab is The DevOps Platform
url: https://github.com/spectrekr/addon-gitlab
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:gitlab
startup: services
homeassistant: 0.113.2
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  22/tcp: ssh port
  80/tcp: null
ports_description:
  22/tcp: ssh port
  80/tcp: Web interface (Not required for Ingress)
discovery:
  - gitlab
auth_api: true
host_network: true
hassio_api: true
hassio_role: manager
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
